### ISSUE TITLE
No module named 'Cython'

### ISSUE THREAD

**Issue by eskape** [jahodfra/IkeaTrainTrack#20]
Running on macOS Sierra, python stalled with brew (python 3 -version: Python 3.6.2).

When I run "sh run.sh" I'm getting the following error.
> 
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
Traceback (most recent call last):
  File "solver.py", line 6, in <module>
    import dynamic
ModuleNotFoundError: No module named 'dynamic'
> 

I've also installed Cython with pip install Cython. And I still get the error. 
Can you help me?

Thanks!
Kishen

**Comment by eskape** [comment]
sudo pip3 install --no-cache-dir Cython solved it!

**Comment by jahodfra** [comment]
I probably should add description how to run the code into Readme.md. Thanks for mentioning this.

**Comment by jahodfra** [comment]
I extended the README.md
